qrcode_index:
    path: /qrcode/{size<\d+>?}/{type}/{content}
    controller: App\Controller\QrcodeController::index
    requirements:
        content: .+
ip_index:
    path: /ip/{ip}
    controller: App\Controller\IpController::index
